brandonlam4237/CSC322_Project

- README.md
- server/.env.example
- server/auth/serializers.py
- server/auth/urls.py
- server/auth/views.py
- server/scripts/secret_key.py
- server/server/settings.py
- server/server/urls.py
- server/user/models.py
- server/user/serializers.py
- server/user/urls.py
- server/user/views.py
**Docs**
Updated README.md and added instructions for:
- Server Setup
- Database Setup
- Environment Variables Setup
- Running the Server
**Endpoints**
Created Auth Endpoints:
- Register
- Logout
Created User Endpoints:
- User List
- Customer List
- Customer Detail
- Blacklisted User List
- Blacklist User
- Activate User
**Random Chores**
- Updated .env.examples to incorporate Django Secret Key
- Changed the access token lifetime from 15 minutes to 2 hours
- Changed the refresh token lifetime from one day to 14 days
> Server Authentication Features and Docs

- client/src/App.tsx
- client/src/components/Button.tsx
- client/src/components/Input.tsx
- client/src/components/Navbar.tsx
- client/src/pages/Login.tsx
- client/src/pages/Register.tsx
- client/src/scss/auth.scss
- client/src/scss/button.scss
- client/src/scss/input.scss
- client/src/scss/radio.scss
In this branch, the following has been implemented: 
- Login and Register Pages 
- Login and Register Form logic + styling
- Custom Button Component to add a layer of convenience
- Custom Input component (this is incomplete and may get scrapped in the future)
Housekeeping notes: 
-  Within ``pages/``, both ``Login.tsx`` and ``Register.tsx`` utilize ``scss/auth.scss`` due to their similarity in structure and functionality
- At the moment, the only way to access the two aforementioned pages is by typing in their respective route path as a URL
Demo:
https://user-images.githubusercontent.com/97417536/230539039-dbdfcf4d-f105-4416-93bb-3cd28e705721.mov
> Feature auth forms

- server/auth/serializers.py
- server/auth/urls.py
- server/auth/views.py
- server/user/serializers.py
- Login Endpoint now provides user details
- A new endpoint was create to retrieve current user data
> Fixed Login Endpoint

- README.md
- client/package.json
- client/src/App.tsx
- client/src/components/Navbar.tsx
- client/src/contexts/AuthContext.tsx
- client/src/pages/Login.tsx
- client/src/pages/Register.tsx
The following has been implemented:
- Authentication related functions like register, login, logout
-  ``AuthContextProvider`` to enable user data access throughout the site
- Conditionally render profile menu button based on login status of user for both desktop and mobile view (mobile view not shown in the recording)
What still needs to be worked on:
- Redirect to home page after login 
-Store the refresh and access tokens in local storage to use them for login persistence upon refreshing/reopning the browser. Waiting on backend team to document the API endpoint responsible for that. 
Short demo of progress: 
https://user-images.githubusercontent.com/97417536/230792617-c3e19239-387a-4a02-ac1a-3b98d2436b62.mov
> Feature client auth

- client/src/components/Navbar.tsx
- client/src/contexts/AuthContext.tsx
- implemented ``useEffect()`` to login user using access token when they reopen browser or refresh their tab
> feat: implement login persistence upon refreshing browser

- requirements.txt
- server/server/settings.py
- Added `http://localhost:3000` to be an allowed host for the server
- Added a new package in requirements.txt
- Please reinstall packages for your environment.
> Fixed CORS Issue

- server/auth/urls.py
- server/items/serializers.py
- server/items/urls.py
- server/items/views.py
- server/server/urls.py
Updated the login data being returned after logging in
- Added product list endpoint
- Added product detail endpoint
- Updated API Documentation for product endpoints
> Product Endpoints

- server/user/urls.py
- server/user/views.py
- Created a new endpoint to add balance
- Must have valid credit card number
- Must not be expired
- Balance must not be negative and under 15000
> Add Balance Endpoint

- server/user/views.py
Fixed blacklist user issue
The new endpoint doesn't require a body, only owner permissions
> fix: Fixed blacklist user endpoint

- client/package-lock.json
- client/package.json
- client/src/App.css
- client/src/components/Button.tsx
- client/src/components/Table.tsx
- client/src/pages/Login.tsx
- client/src/pages/MyBuild.tsx
- client/src/pages/Register.tsx
- client/src/pages/UserRow.tsx
- client/src/scss/auth.scss
- client/src/scss/button.scss
- client/src/scss/mybuild.scss
- client/src/scss/navbar.scss
- client/src/scss/table.scss
- client/src/scss/user-row.scss
- Reworked ``Button`` component styling. The component can take className prop as ``blue-primary``, ``blue-secondary``, ``black-primary``, ``black-secondary``, and ``round``.  For most use cases, the only thing one needs to handle about the button is its width.
https://user-images.githubusercontent.com/97417536/235814549-e01a1402-707c-4ab2-810f-6e7b8379d1c9.mov
- Scaffolding for ``MyBuild`` page. mainly worked on the structure of the page and the ``Table`` component. **There's much work left to be done on this still including but not limited:**
- Selection buttons for each PC part
- Footer section for parts list table to denote the total amount of money
- Javascript logic for adding parts to build, and making API requests for saving, adding, and validating the build
- Conditionally render …
> Feature customize build

- server/items/models.py
- server/user/serializers.py
- server/user/urls.py
- server/user/views.py
- Added orders model
- Added endpoints for submitting orders and getting list of orders
> feat: Added Orders and managing orders endpoints

- client/src/pages/Login.tsx
upon successful login, users are redirected to home page
> Fix login form

- client/src/layouts/RootLayout.tsx
- client/src/pages/AccountDetails.tsx
- client/src/scss/accountDetails.scss
Some things worth noting: 
- Warning and complement values are placeholders
- At the moment, it is not necessary to provide a cardholder name in order to add balance to the user's account
> Feature account details styling

- client/src/App.tsx
- client/src/pages/Cart.tsx
- client/src/services/apiClient.tsx
changed both add to cart and checkout 
fixed app.tsx routes
> Feat order page

- client/src/App.tsx
accidentally added order history page as import and route in ``app.tsx`` so I just removed it
> fix: remove order history route and import

- client/src/components/Box.tsx
- client/src/components/Navbar/NavOptComponents.tsx
- client/src/components/ProductCard.tsx
- client/src/contexts/AuthContext.tsx
- client/src/contexts/PartsListContext.tsx
- client/src/pages/AccountDetails.tsx
- client/src/pages/Approve.tsx
- client/src/pages/Cart.tsx
- client/src/pages/Login.tsx
- client/src/pages/PartPicker.tsx
- client/src/pages/ProductDetail.jsx
- client/src/pages/Products.tsx
- client/src/scss/Box.scss
- client/src/scss/auth.scss
- client/src/scss/button.scss
- client/src/scss/partpicker.scss
- client/src/scss/productCard.scss
- client/src/scss/productDetails.scss
- client/src/services/apiClient.tsx
- Render images properly in the shopping cart
- Add Desktop category for Products menu option in the navbar (formerly known as Components)
- Further styling of product detail page (increased font size, addition of brand name w/ blue accent color, etc)
- Box component to use as an alert banner for various user actions
- Highlight compatible components with the current build when browsing
- Implement red button styling, just use ``red-primary`` or ``red-secondary``
- and more
> Fix client bugs

- server/items/models.py
- server/items/serializers.py
- server/user/serializers.py
> Serialize the comments

- client/src/components/CommentsModal.tsx
- client/src/pages/ProductDetail.jsx
- client/src/scss/commentsModal.scss
- client/src/scss/productDetails.scss
> feat: added comments modal layout

- server/items/admin.py
- server/items/models.py
- server/server/urls.py
- server/user/admin.py
> Admin Panel

- server/server/urls.py
Changed `''` into `'admin/'` for the urlpattern for the admin panel. That fixes the login issue.
> fix: Login issue due to urlpatterns

- client/src/pages/OrderHistory.tsx
- client/src/services/apiClient.tsx
> fix: added missing date in order history

- client/src/pages/AccountDetails.tsx
added alert to balance form for name and cvc
> added alert to balance form for name and cvc

- client/src/pages/AccountDetails.tsx
> fixed previous fix of alerts

- client/src/components/Navbar/Navbar.tsx
- client/src/components/ProductCard.tsx
- client/src/contexts/AuthContext.tsx
- client/src/pages/ProductDetail.jsx
- client/src/scss/button.scss
- client/src/services/apiClient.tsx
- Green button for compatible parts as items are browsed 
- Removed add to cart/build buttons for guest users (and as an extension, removed the need to check for compatibility of parts before rendering them as a grid)
- Fixed bug with ram parts not rendering properly due to ram component with ``id=429``
> Fix partslist

- client/src/components/ProductCard.tsx
- client/src/pages/ProductDetail.jsx
- client/src/pages/Products.tsx
- client/src/services/apiClient.tsx
Added remove from cart buttons for the product page
> added remove from cart to product page and product details

- server/items/models.py
- server/user/views.py
- Removed the calculation in the endpoints themselves
- Resolves #66
> feat: Replaced total_price to calculate discount

- client/src/components/Navbar/Navbar.tsx
- client/src/components/ProductCard.tsx
- client/src/pages/AccountDetails.tsx
- client/src/pages/ProductDetail.jsx
Did customer based conditional rendering on some icons and buttons
> Feat conditional rendering
